dist: bionic
language: php
addons:
  apt:
    packages:
    - php-xmlwriter
php:
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install
- ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
script:
- composer test