version: "3.3"
services:
  www:
    build: php
    container_name: searchy_www
    ports:
      - "80:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
  db:
    image: mysql
    container_name: searchy_db
    environment:
      MYSQL_DATABASE: 'searchy'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: searchy_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  my-db:
